#sudo: false
# travis-ci.org build & test configuration
language: python

matrix:
    include:
        - python: 3.6
        - python: 3.7
        - python: 3.8
    allow_failures:

install:
  - pwd
  - pip install --upgrade pip
  - pip install -e '.[tests]'
  - pip install codecov

script:
  - pytest --cov

after_success:
  - coverage combine
  - codecov

cache: apt
